from __future__ import annotations

from typing import Protocol
from uuid import UUID

from splitwise_manager.domain.entities.splitwise_outbox_entry import OutboxEntry
from splitwise_manager.domain.value_objects.enums import OutboxStatus


class OutboxRepository(Protocol):
    async def add(self, entry: OutboxEntry) -> None: ...
    async def get(self, entry_id: UUID) -> OutboxEntry | None: ...
    async def update(self, entry: OutboxEntry) -> None: ...
    async def list_by_status(self, status: OutboxStatus, *, limit: int = 100) -> list[OutboxEntry]: ...
    async def list_due(self, *, limit: int = 100) -> list[OutboxEntry]: ...
    async def count_by_status(self, status: OutboxStatus) -> int: ...
    async def find_latest_for_payment(self, payment_id: UUID) -> OutboxEntry | None: ...
